---
- name: Update repository nginx
  apt_repository: repo='ppa:nginx/stable' state=present update_cache=yes
  sudo: true

- name: install nginx
  apt:
   name="nginx"
   state=present
   update_cache=true
